### ISSUE TITLE
Don't Close Tab if User Navigated Away

### ISSUE THREAD

**Issue by kbaltrinic** [mukunku/Tab-Close-Gold#12]
### Prerequisites
* A url configured to close after a period of time. (Use the longest--10 sec.--as it make reproducing easier.)
* Have a different url on the clipboard or a bookmark ready to go that you can click on within that ten seconds.

### Steps to reproduce:
1. Open the url configured in the first bullet
2. Once the page loads, navigation to the url/bookmark from the second bullet.

**Expected outcome:**  You can leisurely browse the page you navigated to in step 2.
**Actual outcome:** The page gets close on the 10 second mark as if it were the original page that was configured to be closed.

### Why this is an important bug, not a improbable scenario: Slack!
When I click on a link in slack, it opens a web page in my browser that then causes the slack app to navigate internally to the channel/thread/etc. that the link referred to.  I have Tab-Close Gold configured to close this page in ten seconds with a pattern like `my-org.slack.com/archives/*`

However, the web page used to effect this navigation also displays a link to "open this link in your browser".  If I click on that link it takes me to a url of the form: `app.slack.com/client/[hash]/[hash]` which displays the thread I am interested in in my browser.  But then Tab-Close Gold closes the tab.

My workaround right now is to try to remember to right click on the link and open it in a new tab and let the old one just close.  But realistically, before closing a tab, the app should be checking if the tab is still displaying the content that was intended to be closed or if the user has navigated away from it.

**Comment by mukunku** [comment]
This is something I also experience from time to time and have to remember to open a new tab. 

The reason it works this way was specifically in case a site had a redirect.

For example you could add `ad.doubleclick.net` to the block list and that way you can block all ad redirects that go through that url. Saving you the trouble of blocking each individual site. 

But perhaps I can change it so that if you have a delayed tab close, it cancels it if the tab navigates elsewhere. 

The 10 second delay limitation was so people didnt forget they had a tab marked for closure and start using it just to have it get closed randomly 60+ seconds later.

**Comment by kbaltrinic** [comment]
Interesting, But is no way to differentiate between a user initiated navigation and a redirection?  

I grant your point though, for zoom I definitely want the close even if redirecting.  The marketing team at our company frequently configures the meeting launch page for zoom to redirect to a marketing campaign.  I'm sure that makes sense for prospective customers joining our webinars, but its not too helpful for us on the staff when if it defeats our tab closer!

At least in my case a configuration option would do the trick.  Zoom: close even if page location changes.  Slack: Do not close.

**Comment by mukunku** [comment]
I went through the [chrome api docs](https://developer.chrome.com/docs/extensions/reference/tabs) but couldn't find a way to differentiate between a user navigation vs a redirect. It's possible that I simply couldn't find it.

I'll look into adding a setting for this but it's going to require a UI rework so this will probably take some time to implement.

**Comment by mukunku** [comment]
Going to mark this as won't do due to the complexity. If more need for this comes up I can maybe invest more time into this.
