### ISSUE TITLE
Debugging Help

### ISSUE THREAD

**Issue by kbaltrinic** [mukunku/Tab-Close-Gold#13]
I've noticed that TCG isn't closing tabs anymore on my Chrome 111.0.5563.146 on MocOS Ventura 13.4.1 (22F82).  Looking at the configuration, the last hit on date for any of my patterns was 7/13, when I should see hits on most from the last hour or so and a least within the last day.  Seems like something broke.  Do you have a wiki page on how to debug?  I'm a manager now but five years ago, I was a full stack dev, so I can crack open Dev Tools and have a look but I have no experience with browser plugin development nor the time to come up to speed from scratch on my own, so happy to help but I need pointed in the right direction first.

**Comment by kbaltrinic** [comment]
Update: Simply disabling and re-enabling the plugin seems to have fixed the problem.

**Comment by kbaltrinic** [comment]
This problem occurred again today.

**Comment by mukunku** [comment]
I've noticed mine pausing sometimes too but it was very rare. Any chance you could share your configuration with me and a test url I can test with?

You can debug the code by visiting: chrome://extensions/?id=blhbohajaekmpblcffpkpogkhkmmbbhf and clicking on the **service worker**:
![image](https://github.com/mukunku/Tab-Close-Gold/assets/4502154/8967292e-a1a6-451f-8c38-4194ba55f6a3)

![image](https://github.com/mukunku/Tab-Close-Gold/assets/4502154/6fab5d62-89e2-425f-9a42-9b3aeecc183a)

However the code is minified so it might be hard to debug the production release. A better option would be to download the source code and get it working locally. Sorry I don't have instructions on how to get it working locally right now.

**Comment by mukunku** [comment]
I just released version 3.0.0.0 and completely re-wrote the tab closing engine. Can you give that version a shot and see how it works for you?

I also updated the [readme](https://github.com/mukunku/Tab-Close-Gold#readme) with instructions on how to test the extension locally.
