### ISSUE TITLE
Exact Match

### ISSUE THREAD

**Issue by chrismajewski** [mukunku/Tab-Close-Gold#15]
I may be missing how you accomplish this with RegEx, can't find documentation to confirm.  I tried to add RegEx anchors with no luck.

I'd like to be able to close root site but not details.  e.g.: I'd like to close the gmail inbox but not open individual email.

close
https://mail.google.com/mail/u/0/#inbox/
not
https://mail.google.com/mail/u/0/#inbox/FMfcgzGwHVR...

Anchor statement that didn't work:
^https://mail.google.com/mail/u/0/#inbox$

Possible solutions:

* allow for RegEx anchors
* add in "absolute string" option
* explain to the dumb dumb writing this issue that it's already possible :)

**Comment by mukunku** [comment]
@chrismajewski The regex you provided is working for me `^https://mail.google.com/mail/u/0/#inbox$`

If I go to `gmail.com` or the url itself it closes. But if I visit an actual email like `https://mail.google.com/mail/u/0/#inbox/FMfcgzGwHpQPnvkRwVXPHCkdPdqxtjPc` it does not close the tab.

Did you make sure to check the `IsRegex` option for your search pattern?

**Comment by chrismajewski** [comment]
Cheers, thanks for the response.

I was hoping it was that dumb, that I missed a checkbox, I re-installed the plugin and walked through it again.

![image](https://github.com/mukunku/Tab-Close-Gold/assets/1154737/66543df5-8201-4c97-ae9d-cecc660f9d8a)

It ate the expected fenced in URL but also ate:
https://mail.google.com/mail/u/0/#inbox/FMfcgz...

(update)
In previewing this before sending I noticed that complete message URL was now surviving, works as expected.  I wonder if there is a delay in updating a pattern and it taking effect?

My first pattern was pasted in without the fence (raw URL), it ate everything as it should, I'd then add in the fence, closed and re-opened the editor as to confirm it took the change (it did) expecting that to apply the change.  Expecting it to take effect immediately after change I assumed failure.  In the 5-10 minutes of doing this it's now working as expected.

This issue is resolved but I may have found something else.  I'll leave the plugin installed in the event you'd like to do more testing but I'll close this ticket.  Thank you.

I'm in Brave, Win 10 (latest), just re-installed the plug-in

**Comment by mukunku** [comment]
Glad it's working for you now @chrismajewski . 

In the new 3.0.0.0 version I decoupled setting saving and when the extension picks it up so there is definitely a delay but it's only supposed to be 2 seconds! Definitely not several minutes.

I'll have to keep an eye out for more user issues to see if this is common. However one thing that might help a bit is checking out the extension logs:
<img width="395" alt="image" src="https://github.com/mukunku/Tab-Close-Gold/assets/4502154/f75b7c40-de00-4f09-8f77-17f3b875ded2">

Switching to the `Debug` log level might provide some insight when debugging issues like these:
<img width="243" alt="image" src="https://github.com/mukunku/Tab-Close-Gold/assets/4502154/4b926f72-81b2-424c-9847-b5fbc7aaa0d3">
