### ISSUE TITLE
Add new option.

### ISSUE THREAD

**Issue by 1stGitH** [mukunku/Tab-Close-Gold#16]
Extension is working perfectly but can you add a select option for each url in blocklist :
  - Block tab with url match with block list(already have)
  - Block tab with url match with block list and tab have no back url(almost ads do open new tab and redirect to a page so need to block but sometime i need go to ads page by myself (this tab always have back url) so i don't need to block).
Thanks very much.

**Comment by mukunku** [comment]
Sorry but since there doesn't seem to be more interest in this feature I'm not planning on adding it any time soon. Happy to revisit in the future, though.
