### ISSUE TITLE
Possible to add a "delay" option?

### ISSUE THREAD

**Issue by jzvi12** [mukunku/Tab-Close-Gold#2]
Great extension! I understand the current use case which is perfect for closing URLs redirecting to Ads, but there are other cases where you want to apply a delay for a given time (could be seconds or minutes) before automatically closing a tab when URL matches criteria. Is it possible to add a "delay" option? - Thanks in advance!

**Comment by mukunku** [comment]
Coming soon #6

**Comment by mukunku** [comment]
This is now available with v2.0.0!
