### ISSUE TITLE
Closing the last tab does not close the browser 

### ISSUE THREAD

**Issue by leodoi3** [mukunku/Tab-Close-Gold#3]
I tested it on Edge.  If I only have 1 tab open and I visit one of the enabled sites , it will close it but still keep the browser open.  Unless if I just close the last tab manually then the browser closes with it. Could you add an option so closing the last tab will also close the browser?

**Comment by mukunku** [comment]
This is actually a safety feature added in 1.2.0.0. 

If you have "Continue where I left off" enabled in your browser then if the extension closes the last tab (and consequently the browser) the same tab will be launched the next time the browser is started. Which the extension will then auto close again which will close the browser again right after its launched. Thus preventing you from starting your browser unless you start in safe mode.

So not sure if your request can be done.

**Comment by mukunku** [comment]
@leodoi3 version 3.0.0.0 adds the ability to close the browser when the last tab is closed
