### ISSUE TITLE
Request: Match by tab title

### ISSUE THREAD

**Issue by leodoi3** [mukunku/Tab-Close-Gold#5]
Instead of checking the URL could you add an option to check the tab title?  Also add an option to use Regex.

**Comment by mukunku** [comment]
I just released version 3.0.0.0 and it adds the ability to [match by title](https://github.com/mukunku/Tab-Close-Gold/wiki#blacklist-a-url-or-page-title-from-the-options-page)!
![image](https://github.com/mukunku/Tab-Close-Gold/assets/4502154/8c0a9057-3d21-4ef9-96fb-649953fb9a3f)
