### ISSUE TITLE
Request: Temporarily disable shortcut

### ISSUE THREAD

**Issue by leodoi3** [mukunku/Tab-Close-Gold#9]
Could you add a keyboard shortcut that would disable the rules for x seconds?

**Comment by mukunku** [comment]
I'll take a look but no promises on timing. In the meantime maybe this could help? https://chrome.google.com/webstore/detail/disable-extensions-tempor/lcfdefmogcogicollfebhgjiiakbjdje?hl=en

**Comment by mukunku** [comment]
Sorry, unless there's more desire, i'm not going to implement this for the time being.
